merge add-docker into main
gghglr/java-shareit pull request #9
Opened 2024-03-10 09:07 UTC by gghglr

2024-03-10 18:39 UTC, avlin87 requested changes
Привет, Алексей,
Работа выглядит хорошо.
Тестовые классы не нужно было удалять - верни их, пожалуйста.

P.S.
Есть ощущение дежавю, словно точно такие же классы уже встречались в других работах.

2024-03-10 18:39 UTC, avlin87 commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +                builder
`можно лучше`
первый вызываемый метод обычно не отделяют новой строкой от объекта:
```
builder.uriTemplateHandler(new DefaultUriBuilderFactory(serverUrl + API_PREFIX))
...
```

2024-03-11 09:42 UTC, gghglr commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +                builder
Не знаю почему дежавю, BaseClient был дан всем одинаковый, а все методы в контроллерах в gateway перенесены из старых контроллеров. Реализацию client делал на основе BookingClient, который так же был дан изначально

2024-03-11 18:26 UTC, avlin87 approved these changes
Работу принимаю.

2024-03-15 09:14 UTC, merged